[2023-12-11T06:06:50.455+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS manual__2023-12-11T06:03:56.676264+00:00 [queued]>
[2023-12-11T06:06:50.471+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS manual__2023-12-11T06:03:56.676264+00:00 [queued]>
[2023-12-11T06:06:50.471+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-11T06:06:50.487+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): IT_website_to_GCS> on 2023-12-11 06:03:56.676264+00:00
[2023-12-11T06:06:50.512+0000] {standard_task_runner.py:57} INFO - Started process 129 to run task
[2023-12-11T06:06:50.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'IT_website_to_GCS', 'manual__2023-12-11T06:03:56.676264+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmp4k3s0ckx']
[2023-12-11T06:06:50.523+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask IT_website_to_GCS
[2023-12-11T06:06:50.591+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS manual__2023-12-11T06:03:56.676264+00:00 [running]> on host 5725e2187d30
[2023-12-11T06:06:50.693+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='IT_website_to_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T06:03:56.676264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-11T06:03:56.676264+00:00'
[2023-12-11T06:06:50.799+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 78, in IT_website_to_GCS
    print(f"The main url is: {mainurl}")
NameError: name 'mainurl' is not defined
[2023-12-11T06:06:50.813+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=IT_website_to_GCS, execution_date=20231211T060356, start_date=20231211T060650, end_date=20231211T060650
[2023-12-11T06:06:50.828+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task IT_website_to_GCS (name 'mainurl' is not defined; 129)
[2023-12-11T06:06:50.891+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
