[2023-12-11T05:34:30.065+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T05:34:30.077+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T05:34:30.077+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-11T05:34:30.092+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): IT_website_to_GCS> on 2023-12-10 02:00:00+00:00
[2023-12-11T05:34:30.109+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-12-11T05:34:30.117+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'IT_website_to_GCS', 'scheduled__2023-12-10T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmp6qpt0oem']
[2023-12-11T05:34:30.118+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask IT_website_to_GCS
[2023-12-11T05:34:30.186+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [running]> on host 7db0f6f3c89a
[2023-12-11T05:34:30.289+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='IT_website_to_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-10T02:00:00+00:00'
[2023-12-11T05:34:30.424+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 74, in IT_website_to_GCS
    main = Scraping(mainURL, "get_cat", source)
  File "/opt/airflow/dags/article_ingestion.py", line 37, in __init__
    req = requests.get(self.url)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-12-11T05:34:30.438+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=IT_website_to_GCS, execution_date=20231210T020000, start_date=20231211T053430, end_date=20231211T053430
[2023-12-11T05:34:30.453+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task IT_website_to_GCS (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 62)
[2023-12-11T05:34:30.488+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-11T05:42:50.156+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T05:42:50.190+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T05:42:50.190+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-11T05:42:50.216+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): IT_website_to_GCS> on 2023-12-10 02:00:00+00:00
[2023-12-11T05:42:50.237+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2023-12-11T05:42:50.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'IT_website_to_GCS', 'scheduled__2023-12-10T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmp7lb04fnr']
[2023-12-11T05:42:50.248+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask IT_website_to_GCS
[2023-12-11T05:42:50.367+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [running]> on host b6f6ead67d56
[2023-12-11T05:42:50.516+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='IT_website_to_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-10T02:00:00+00:00'
[2023-12-11T05:42:50.655+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 76, in IT_website_to_GCS
    main = Scraping(mainURL, "get_cat", source)
  File "/opt/airflow/dags/article_ingestion.py", line 39, in __init__
    req = requests.get(self.url)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-12-11T05:42:50.672+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=IT_website_to_GCS, execution_date=20231210T020000, start_date=20231211T054250, end_date=20231211T054250
[2023-12-11T05:42:50.690+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task IT_website_to_GCS (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 60)
[2023-12-11T05:42:50.738+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-11T06:04:10.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T06:04:10.857+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T06:04:10.858+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-11T06:04:10.880+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): IT_website_to_GCS> on 2023-12-10 02:00:00+00:00
[2023-12-11T06:04:10.897+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2023-12-11T06:04:10.915+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'IT_website_to_GCS', 'scheduled__2023-12-10T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmpiiezq3w3']
[2023-12-11T06:04:10.916+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask IT_website_to_GCS
[2023-12-11T06:04:11.039+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [running]> on host 5725e2187d30
[2023-12-11T06:04:11.180+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='IT_website_to_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-10T02:00:00+00:00'
[2023-12-11T06:04:11.325+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 80, in IT_website_to_GCS
    main = Scraping(mainURL, "get_cat", source)
  File "/opt/airflow/dags/article_ingestion.py", line 43, in __init__
    req = requests.get(self.url)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-12-11T06:04:11.343+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=IT_website_to_GCS, execution_date=20231210T020000, start_date=20231211T060410, end_date=20231211T060411
[2023-12-11T06:04:11.368+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task IT_website_to_GCS (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 84)
[2023-12-11T06:04:11.409+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-11T06:49:42.143+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T06:49:42.157+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [queued]>
[2023-12-11T06:49:42.158+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-11T06:49:42.174+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): IT_website_to_GCS> on 2023-12-10 02:00:00+00:00
[2023-12-11T06:49:42.198+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-12-11T06:49:42.205+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'IT_website_to_GCS', 'scheduled__2023-12-10T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmpbwm5sxve']
[2023-12-11T06:49:42.206+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask IT_website_to_GCS
[2023-12-11T06:49:42.296+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.IT_website_to_GCS scheduled__2023-12-10T02:00:00+00:00 [running]> on host d6a4626c6414
[2023-12-11T06:49:42.409+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='IT_website_to_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-10T02:00:00+00:00'
[2023-12-11T06:49:42.520+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 74, in IT_website_to_GCS
    main = Scraping(mainURL, "get_cat", source)
  File "/opt/airflow/dags/article_ingestion.py", line 37, in __init__
    req = requests.get(self.url)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2023-12-11T06:49:42.537+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=IT_website_to_GCS, execution_date=20231210T020000, start_date=20231211T064942, end_date=20231211T064942
[2023-12-11T06:49:42.554+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task IT_website_to_GCS (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 108)
[2023-12-11T06:49:42.582+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
