[2023-12-12T03:57:02.494+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T03:57:02.508+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T03:57:02.509+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-12T03:57:02.527+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_Pinecone_Index> on 2023-12-11 02:00:00+00:00
[2023-12-12T03:57:02.552+0000] {standard_task_runner.py:57} INFO - Started process 265 to run task
[2023-12-12T03:57:02.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'create_Pinecone_Index', 'scheduled__2023-12-11T02:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmpfga8zp54']
[2023-12-12T03:57:02.563+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_Pinecone_Index
[2023-12-12T03:57:02.632+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [running]> on host bbfe106ef65d
[2023-12-12T03:57:02.748+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='create_Pinecone_Index' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T02:00:00+00:00'
[2023-12-12T03:57:38.121+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/article_ingestion.py", line 96, in create_Pinecone_Index
    pinecone.create_index(my_index, dimension = embed_dim, metric="euclidean", pod_type="p1")
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/manage.py", line 118, in create_index
    api_instance.create_index(create_request=CreateRequest(
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model_utils.py", line 49, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model/create_request.py", line 297, in __init__
    self.dimension = dimension
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model_utils.py", line 188, in __setattr__
    self[attr] = value
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model_utils.py", line 488, in __setitem__
    self.set_attribute(name, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model_utils.py", line 160, in set_attribute
    value = validate_and_convert_types(
  File "/home/airflow/.local/lib/python3.8/site-packages/pinecone/core/client/model_utils.py", line 1557, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
pinecone.core.client.exceptions.ApiTypeError: Invalid type for variable 'dimension'. Required value type is int and passed type was str at ['dimension']
[2023-12-12T03:57:38.137+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=IT_to_Pinecone_dag, task_id=create_Pinecone_Index, execution_date=20231211T020000, start_date=20231212T035702, end_date=20231212T035738
[2023-12-12T03:57:38.152+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task create_Pinecone_Index (Invalid type for variable 'dimension'. Required value type is int and passed type was str at ['dimension']; 265)
[2023-12-12T03:57:38.211+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-12T04:31:05.192+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T04:31:05.207+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T04:31:05.208+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-12T04:31:05.232+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_Pinecone_Index> on 2023-12-11 02:00:00+00:00
[2023-12-12T04:31:05.252+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2023-12-12T04:31:05.258+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'create_Pinecone_Index', 'scheduled__2023-12-11T02:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmp54gr1s2b']
[2023-12-12T04:31:05.262+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_Pinecone_Index
[2023-12-12T04:31:05.334+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [running]> on host 271b37441abd
[2023-12-12T04:31:05.433+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='create_Pinecone_Index' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T02:00:00+00:00'
[2023-12-12T04:32:01.089+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-12-12T04:32:01.103+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=IT_to_Pinecone_dag, task_id=create_Pinecone_Index, execution_date=20231211T020000, start_date=20231212T043105, end_date=20231212T043201
[2023-12-12T04:32:01.157+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-12T05:00:41.589+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T05:00:41.604+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [queued]>
[2023-12-12T05:00:41.604+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-12-12T05:00:41.624+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_Pinecone_Index> on 2023-12-11 02:00:00+00:00
[2023-12-12T05:00:41.649+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-12-12T05:00:41.656+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'IT_to_Pinecone_dag', 'create_Pinecone_Index', 'scheduled__2023-12-11T02:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/article_ingestion.py', '--cfg-path', '/tmp/tmp452b7zhy']
[2023-12-12T05:00:41.659+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_Pinecone_Index
[2023-12-12T05:00:41.733+0000] {task_command.py:410} INFO - Running <TaskInstance: IT_to_Pinecone_dag.create_Pinecone_Index scheduled__2023-12-11T02:00:00+00:00 [running]> on host 2b4786193316
[2023-12-12T05:00:41.833+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IT_to_Pinecone_dag' AIRFLOW_CTX_TASK_ID='create_Pinecone_Index' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T02:00:00+00:00'
[2023-12-12T05:01:37.560+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-12-12T05:01:37.581+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=IT_to_Pinecone_dag, task_id=create_Pinecone_Index, execution_date=20231211T020000, start_date=20231212T050041, end_date=20231212T050137
[2023-12-12T05:01:37.677+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
